### PR TITLE
Add anchors to subsections

### LINKED ISSUE #74: Subsection Anchors
The other day, I tired linking `git log -S`, but I couldn't.  I had to link [`git log`](http://gitref.org/inspect/#log).  May I add subsection anchors?

h4-anchor

``` html
<h4>
  git log -S
  <small>filter by introduced diff</small>
  <a name="log-s"></a>
</h4>
```

Thoughts?  Thanks!

### PR DESCRIPTION
**Pull request by simeonwillbanks**
Fixes #74

e.g. /inspect/#log-s

screen shot 2014-01-09 at 7 34 58 pm

### CODE REVIEW

**Comment by randomecho** [comment]
If you wanted less markup, you could go with something like:

```
<h4 id="diff-cached">
```

**Comment by simeonwillbanks** [comment]
I suggested and used anchors because the `h2` tags [use anchors](https://github.com/simeonwillbanks/git-reference/blob/2b328650e926e9915f49e5afa35a99ec9a59e62d/basic/index.html#L44).

However, `id` attributes are fine with me.  Should I refactor?

Thanks! :smile:

**Comment by matthewmccullough** [comment]
@simeonwillbanks Happy to go either way.  I don't want to get in the way of this shipping.  I'd love this to have less markup, so if that isn't a bunch of work, let's do it.  If it is a bunch of work, then lets ship as is.

Thanks for this valuable contribution for accessibility's sake.

**Comment by simeonwillbanks** [comment]
@matthewmccullough You're welcome!

**Comment by bry4n** [comment]
:+1:

**Comment by simeonwillbanks** [comment]
@matthewmccullough If you have a moment, can you please review my last commit? I hope it's ready to :ship:.  If not, let me know.

Thank you for your time! :smile:

**Comment by matthewmccullough** [comment]
@simeonwillbanks Thanks for the reminder. Got the :+1: so it is now :ship:ed!

**Comment by simeonwillbanks** [comment]
@matthewmccullough You're welcome and thank you for :ship: ing. :metal:

**Pull request merged**
