### PR TITLE
Convert to CC-BY-3.0

### PR DESCRIPTION
**Pull request by tlberglund**
This brings gitref.org in line with other OSS Github Training repos.

### CODE REVIEW

**Comment by matthewmccullough** [comment]
:+1:

**Comment by tlberglund** [comment]
@matthewmccullough Thanks, man. Really just wanted some other human who was in the loop last fall to double-check me.

**Comment by matthewmccullough** [comment]
The timing on this is hilarious.  I added licenses to almost all my open source repos yesterday.

**Comment by tlberglund** [comment]
Heh.

**Pull request merged**
