### PR TITLE
Added remark about stashing untracked files

### LINKED ISSUE #68: git stash doesn't stash away unversioned files
You should mention that `git stash` doesn't stash away files that are not in the index yet. It can cause much trouble if you e.g. do a git clean -dfx on the super-urgent-bugfix branch. However, 1.7.7 and up has `git stash -u` to do this.

### PR DESCRIPTION
**Pull request by gergelypolonkai**
To fix #68 as requested.

### CODE REVIEW

**Comment by randomecho** [comment]
Nice caveat note. Some suggestions:
- "doesn't save it" → "won't save them" or "will not include them" since we're talking about possibly multiple files.
- "either add stage those files" → "either first add the untracked files to the stage", personally it was the "add stage" part of the sentence that sounded off, but actual veterans reviewing this might hear it differently.
- "to stash also unversioned files" → "to also stash unversioned files" or "to include untracked files in the stash".

**Comment by gergelypolonkai** [comment]
“add stage” was a mistake on my part, the word “add” remained there by accident. On the other modifications, thank you for your comments, your proposed sentences feel much better.

**Comment by matthewmccullough** [comment]
I like the current version of this. Shall I :shipit: @github/training-team ?

**Comment by tlberglund** [comment]
:shipit:

**Comment by jordanmccullough** [comment]
:ship: this. :+1:

**Pull request merged**
