### PR TITLE
Tip about tags not coming down the aisle unless you call for them

### PR DESCRIPTION
**Pull request by randomecho**
Tags are so incidental they are not normally slurped with the
usual fetch or push commands. A little heads up.

Also adds a nutshell inline with the rest of the cards.

### CODE REVIEW

**Comment by matthewmccullough** [comment]
Tags on commits that are also referenced by commits pointed to by branches seem to be retrieved by the default refspec. So, just thinking, we might want to nuance the `fetch --tags` phrasing to give that level of detail. Thoughts?

**Comment by brntbeer** [comment]
:+1: for specification on the `--tags` flag as well, and didn't think about this use case originally. I think pointing out that a push without the tags flag is very important.

Also, the idea of pointing out that although tags by default will come down on a `git fetch` (where as they dont go up by default on a push) is good, but if you want all tags (instead of tags that point to branch heads that are being followed), use the `git fetch --tags` to be sure you're getting everything.

Great catch, as always!

**Comment by randomecho** [comment]
Does [that suggested blockquote](https://github.com/randomecho/git-reference/commit/690a441c2558749426962ac6bfe6bb74acb43b2a#commitcomment-2328175) address what @matthewmccullough brought up in any way? Not sure.

**Comment by matthewmccullough** [comment]
Yup, @randomecho. The https://github.com/randomecho/git-reference/commit/690a441c2558749426962ac6bfe6bb74acb43b2a#commitcomment-2328175 addresses the `fetch` and pull default behavior of tags that are not reachable by branch heads.

**Pull request merged**
