### PR TITLE
笔误：知识 > 只是

### PR DESCRIPTION
**Pull request by nuysoft**

### CODE REVIEW

**Comment by brntbeer** [comment]
Pinging @sdq, you helped out with the `cn` translation on https://github.com/github/training-kit, could you give this a look over.

Similarly, @nuysoft: what is this actual change?

**Comment by sdq** [comment]
@brntbeer Yes, this is a little mistake in translation.

**Comment by brntbeer** [comment]
@sdq if you don't mind then, could you explain the diff?

**Comment by sdq** [comment]
@brntbeer this pull request change the word ‘知识’ to ‘只是’. The original translation for this word is wrong.

**Comment by brntbeer** [comment]
@sdq sounds good since the original translation was wrong.

Thanks @nuysoft as well!

**Pull request merged**
